export const MESSAGE = {
  TYPE: {
    JOIN_LOBBY: "JOIN_LOBBY",
    JOIN_LOBBY_ACK: "JOIN_LOBBY_ACK",

    GET_PEER_LIST: "GET_PEER_LIST",
    GET_PEER_LIST_ACK: "GET_PEER_LIST_ACK",
    PEER_LIST_CHANGED: "PEER_LIST_CHANGED",

    GET_STUN_TURN_INFO: "GET_STUN_TURN_INFO",
    GET_STUN_TURN_INFO_ACK: "GET_STUN_TURN_INFO_ACK",

    WEBRTC_OFFER: "WEBRTC_OFFER",
    WEBRTC_ANSWER: "WEBRTC_ANSWER",
    ICE_CANDIDATE: "ICE_CANDIDATE",

    CALL_STARTED: "CALL_STARTED",

    HANG_UP: "HANG_UP",
  },
};
